language: python
python:
    - "2.7"
install:
    - pip install -U pip
    - pip install -U setuptools
before_script:
    - mysql -u root -e "CREATE DATABASE shsmd;"
    - mysql -u root -e "CREATE USER 'shsmd'@'%' IDENTIFIED by 'shsmd';"
    - mysql -u root -e "GRANT ALL ON shsmd.* TO 'shsmd'@'%';"
script: 
    - python setup.py test
services:
    - mysql
